name: Run Robot Tests on Push
permissions:
  contents: read
  pages: write
  id-token: write
# 🔸 Khi nào workflow chạy
on:
  push:             # mỗi khi bạn push code
    branches:
      - bugfix        # bạn có thể đổi thành branch khác (VD: dev)
  workflow_dispatch: # cho phép bấm "Run workflow" thủ công trong tab Actions

jobs:
  run-tests:
    runs-on: ubuntu-latest    # tạo máy ảo Ubuntu sạch

    steps:
      # 1️⃣ Lấy code trong repo về
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Cài Python (chạy được Robot Framework)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # hoặc 3.10, tùy môi trường bạn dùng local

      # 3️⃣ Cài các thư viện cần thiết (có thể định nghĩa trong requirements.txt)
      - name: Install dependencies
        run: |
          pip install robotframework
          pip install selenium
          pip install robotframework-seleniumlibrary
          pip install robotframework-datadriver
          pip install robotframework-requests
          pip install robotframework-extensions-collection
          pip install robotframework-jsonlibrary
          pip install robotframework-faker
          pip install allure-robotframework
      
      - name: Install chromedriver via webdriver_manager
        run: |
          python -m pip install --upgrade pip
          pip install webdriver-manager
          CHROME_DRIVER_PATH=$(python -c "from webdriver_manager.chrome import ChromeDriverManager; print(ChromeDriverManager().install())")
          sudo mv "$CHROME_DRIVER_PATH" /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # 4️⃣ Chạy Robot test + ghi kết quả Allure
      - name: Run Robot tests
        run: |
          mkdir -p results
          robot --listener allure_robotframework:results/allure-results -d results tests/authentication/signin.robot

      # 5️⃣ Generate Allure HTML report
      - name: Generate Allure report
        run: |
          pip install allure-robotframework
          npm install -g allure-commandline --save-dev
          allure generate results/allure-results -o results/allure-report --clean

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: results/allure-report
      
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4   

      - name: Upload Allure raw results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: results/allure-results
