name: Run Robot Tests on Push

# 🔸 Khi nào workflow chạy
on:
  push:             # mỗi khi bạn push code
    branches:
      - bugfix        # bạn có thể đổi thành branch khác (VD: dev)
  workflow_dispatch: # cho phép bấm "Run workflow" thủ công trong tab Actions

jobs:
  run-tests:
    runs-on: ubuntu-latest    # tạo máy ảo Ubuntu sạch

    steps:
      # 1️⃣ Lấy code trong repo về
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Cài Python (chạy được Robot Framework)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # hoặc 3.10, tùy môi trường bạn dùng local

      # 3️⃣ Cài các thư viện cần thiết (có thể định nghĩa trong requirements.txt)
      - name: Install dependencies
        run: |
          pip install robotframework
          pip install selenium
          pip install robotframework-seleniumlibrary
          pip install robotframework-datadriver
          pip install robotframework-requests
          pip install robotframework-extensions-collection
          pip install robotframework-jsonlibrary
          pip install robotframework-faker
          pip install allure-robotframework

      # 4️⃣ Chạy Robot test + ghi kết quả Allure
      - name: Run Robot tests
        run: |
          mkdir -p results
          robot --listener allure_robotframework:results/allure-results -d results tests/authentication/signin.robot

      # 5️⃣ Generate Allure HTML report
      - name: Generate Allure report
        run: |
          pip install allure-robotframework
          allure generate results/allure-results -o results/allure-report --clean

      # 6️⃣ (Tuỳ chọn) Upload report làm artifact để tải về
      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: results/allure-report

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" | grep -A3 "$CHROME_VERSION" | grep "url" | grep "linux64" | head -1 | cut -d'"' -f4)
          wget -q -O /tmp/chromedriver.zip $DRIVER_VERSION
          sudo unzip -o /tmp/chromedriver.zip -d /usr/local/bin/      
